name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
      
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          command_timeout: 30m
          port: 22
          script: |
            # Go to app directory
            cd /home/theoceangame-api/htdocs/api.theoceangame.com

            # Ensure we are on master branch
            git fetch origin main
            git reset --hard origin/main

        

            # Install dependencies
               npm install

         
            # Export environment variables
            #NEXT_PUBLIC_API_URL=https://api.theoceangame.com
            # export NODE_ENV=${{ secrets.NODE_ENV }}
            # export PORT=${{ secrets.PORT }}
            # export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            # export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            # export PROD_DB_STRING=${{ secrets.PROD_DB_STRING }}
            # export DB_NAME=${{ secrets.DB_NAME }}
            # export JWT_SECRET=${{ secrets.JWT_SECRET }}
            # export NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
            # export NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            # export FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}
            # export FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}
            # export NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}

            # Build Next.js project
            #npm run build

            # Restart app with PM2
            pm2 restart all 
            #pm2 start npm --name " tog-admin " -- start -- --port 3002
            #sudo nginx -t
           # sudo systemctl reload nginx
